version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localstack-test"
s3_bucket = "localstack-test"
s3_prefix = "localstack-test"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
