AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: localstack-test

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: "'*'"
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Handler: index.handler
      CodeUri: dist/my-function
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /items
            Method: GET 
            RestApiId: !Ref ApiGateway